# Default values for 11st-backoffice.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

# dev, alp, real
environment: dev

image:
  repository: 446804614856.dkr.ecr.ap-northeast-2.amazonaws.com
  imageName: 11st-registry
  tag: sample-spring-v0.0.2
  pullPolicy: Always

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

namespace: default

keystore:
  secretName:

env:
  springProfile: dev
  javaOptions: -Xms1024m -Xmx1024m
  useProxyOptions:
  proxyOptions:
  nonProxyOptions:

service:
  enabled: true
  type: ClusterIP
  port: 8080
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
# - port: "5701"
#   targetPort: hazelcast
#   protocol: TCP
#   name: hazelcast

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: sample-spring.tool.k8s.11stdev.io
      paths:
        - path: /

  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

hostAliases: []
# - ip: "192.168.1.10"
#   hostnames:
#   - "example.com"
#   - "www.example.com"

persistence:
  enabled: false
#  storageClass: pv-nas-
#  accessMode: ReadWriteMany
#  size: 8Gi
#  annotations: {}

extraVolumes: |
#  - name: data
#    persistentVolumeClaim:
#      claimName: pvc-nas-

extraVolumeMounts: |
#  - name: data
#    mountPath: /data

resources:
  limits:
    cpu: 500m
    memory: 1024Mi
  requests:
    cpu: 500m
    memory: 1024Mi

tolerations:
  - key: node.kubernetes.io/not-ready
    effect: NoExecute
    tolerationSeconds: 30
  - key: node.kubernetes.io/unreachable
    effect: NoExecute
    tolerationSeconds: 30

## @param livenessProbe - object - optional
# livenessProbe:
# probe: exec, httpGet, tcpSocket
#livenessProbe:
#  tcpSocket:
#    port: 8080
#  initialDelaySeconds: 10
#  periodSeconds: 5
#  failureThreshold: 3
#  successThreshold: 1
#  timeoutSeconds: 1

## @param readinessProbe - object - optional
# readinessProbe:
# probe: exec, httpGet, tcpSocket
#readinessProbe:
#  httpGet:
#    path: /
#    port: 8080
#  initialDelaySeconds: 10
#  periodSeconds: 5
#  failureThreshold: 3
#  successThreshold: 1
#  timeoutSeconds: 1
