version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk8
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region ap-northeast-2)
  build:
    commands:
      - echo Build Starting on `date`
      - mvn clean install
      - docker build -t 446804614856.dkr.ecr.ap-northeast-2.amazonaws.com/11st-registry:${TAG_NAME} .
      - docker push 446804614856.dkr.ecr.ap-northeast-2.amazonaws.com/11st-registry:${TAG_NAME}

